using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace AgentPack.Core;

/// <summary>
/// catalog.lock.yaml — generated by 'agentpack catalog lock' (normally in catalog-repo CI).
/// Holds content checksums so authors never hand-maintain hashes in manifests, and pins
/// resolved external refs. Committed next to catalog.yaml.
/// </summary>
public sealed class CatalogLockFile
{
    public string SchemaVersion { get; set; } = "1";
    public List<CatalogLockEntry> Entries { get; set; } = [];

    public CatalogLockEntry? Find(string assetId) =>
        Entries.FirstOrDefault(x => x.Id.Equals(assetId, StringComparison.OrdinalIgnoreCase));

    public static string PathFor(string catalogPath) =>
        Path.Combine(Path.GetDirectoryName(Path.GetFullPath(catalogPath))!, "catalog.lock.yaml");

    public static CatalogLockFile Load(string path)
    {
        if (!File.Exists(path)) return new CatalogLockFile();
        return Deserializer.Deserialize<CatalogLockFile>(File.ReadAllText(path)) ?? new CatalogLockFile();
    }

    public void Save(string path)
    {
        Entries = Entries.OrderBy(x => x.Id, StringComparer.Ordinal).ToList();
        File.WriteAllText(path, "# Generated by 'agentpack catalog lock'. Do not edit by hand.\n" + Serializer.Serialize(this));
    }

    private static readonly IDeserializer Deserializer = new DeserializerBuilder()
        .WithNamingConvention(CamelCaseNamingConvention.Instance)
        .IgnoreUnmatchedProperties()
        .Build();

    private static readonly ISerializer Serializer = new SerializerBuilder()
        .WithNamingConvention(CamelCaseNamingConvention.Instance)
        .ConfigureDefaultValuesHandling(DefaultValuesHandling.OmitNull | DefaultValuesHandling.OmitEmptyCollections)
        .Build();
}

public sealed class CatalogLockEntry
{
    public string Id { get; set; } = "";
    public string Kind { get; set; } = "";
    public string SourceType { get; set; } = "local";
    public string? Url { get; set; }
    public string? Ref { get; set; }
    public string? Checksum { get; set; }
}
